baseURL = '/'
defaultContentLanguage = 'zh-Hans'
defaultContentLanguageInSubdir = true
disableDefaultLanguageRedirect = false
disableLanguages = []
title = "梦石's Blog"

theme = 'hugo-theme-mage'

[markup]
  _merge = 'deep'

# Settings of caches when hosted on GitHub Pages.
[caches]
  [caches.images]
    dir = ':cacheDir/images'
