[en]
  contentDir = 'content/en'
  locale = 'en'
  label = 'English'
  weight = 2

[zh-Hans]
  contentDir = 'content/zh-Hans'
  hasCJKLanguage = true
  locale = 'zh-Hans'
  label = '简体中文'
  weight = 1
